# config.yaml
device:
  uri: "Android:///192.168.31.33:46747"   # 设备连接 ID
#  uri: "Android:///192.168.31.102:37781"   # 设备连接 ID

output:
  json_filename: "ocr_result.json"        # 保存的 JSON 文件名
  base_dir: "截屏"                         # 文件基础位置（截图保存根目录）
  # 查询结果的 JSON 文件名称
  query_json_filename: "query_result.json"